[2023-10-03T07:43:52.104+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:43:52.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:43:52.106+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:43:52.106+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:43:52.113+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:43:52.112+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:43:52.114+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:43:52.128+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.028 seconds
[2023-10-03T07:44:22.371+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:44:22.373+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:44:22.377+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:22.376+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:44:22.386+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:22.385+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:44:22.387+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:44:22.426+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.060 seconds
[2023-10-03T07:44:52.936+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:44:52.937+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:44:52.939+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:52.938+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:44:52.950+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:44:52.948+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:44:52.951+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:44:52.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.049 seconds
[2023-10-03T07:45:23.238+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:45:23.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:45:23.269+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:23.268+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:45:23.329+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:23.321+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:45:23.331+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:45:23.359+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.137 seconds
[2023-10-03T07:45:53.890+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:45:53.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:45:53.894+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:53.894+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:45:53.901+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:45:53.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:45:53.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:45:53.925+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.038 seconds
[2023-10-03T07:50:23.836+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:50:23.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:50:23.861+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:50:23.860+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:50:23.868+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:50:23.866+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:50:23.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:50:23.886+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.060 seconds
[2023-10-03T07:50:54.051+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:50:54.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:50:54.057+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:50:54.057+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:50:54.068+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:50:54.065+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/producer.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/producer.py", line 9, in <module>
    start_date = datetime(2022, 1, 1),
NameError: name 'datetime' is not defined
[2023-10-03T07:50:54.068+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:50:54.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.046 seconds
[2023-10-03T07:51:11.670+0000] {processor.py:157} INFO - Started process (PID=141) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:51:11.675+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:51:11.685+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.684+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:51:11.701+0000] {processor.py:839} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:51:11.783+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.783+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-03T07:51:11.788+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.787+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-03T07:51:11.790+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.790+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-10-03T07:51:11.790+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.790+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:producer' as access control is unset.
[2023-10-03T07:51:11.790+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.790+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-03T07:51:11.797+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.797+0000] {dag.py:2937} INFO - Creating ORM DAG for producer
[2023-10-03T07:51:11.803+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:11.803+0000] {dag.py:3696} INFO - Setting next_dagrun for producer to 2023-10-02T00:00:00+00:00, run_after=2023-10-03T00:00:00+00:00
[2023-10-03T07:51:11.815+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.158 seconds
[2023-10-03T07:51:42.194+0000] {processor.py:157} INFO - Started process (PID=200) to work on /opt/airflow/dags/producer.py
[2023-10-03T07:51:42.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/producer.py for tasks to queue
[2023-10-03T07:51:42.200+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:42.199+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/producer.py
[2023-10-03T07:51:42.211+0000] {processor.py:839} INFO - DAG(s) dict_keys(['producer']) retrieved from /opt/airflow/dags/producer.py
[2023-10-03T07:51:42.239+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:42.239+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2023-10-03T07:51:42.253+0000] {logging_mixin.py:151} INFO - [2023-10-03T07:51:42.253+0000] {dag.py:3696} INFO - Setting next_dagrun for producer to 2023-10-02T00:00:00+00:00, run_after=2023-10-03T00:00:00+00:00
[2023-10-03T07:51:42.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/producer.py took 0.077 seconds
